### PR TITLE
#958 avoid referencing uninitalized

### PR DESCRIPTION
**Pull request by WingZer0o**
#958

### CODE REVIEW

**Comment by WingZer0o** [comment]
Disregard this PR, late wrong command.

**Comment by bartlomieju** [comment]
@WingZer0o this looks good, could you tend to that lint error that's holding up CI?

**Comment by WingZer0o** [comment]
@bartlomieju sorry about leaving that hanging, I was working through those and got tied up.

**Comment by aapoalas** [comment]
One possible thing is that if you have two different email addresses (say, gmail for OSS and @company.com for work) and you've accidentally committed your OSS contribution with the work email, it will not work.

**Pull request closed without merging**
