### PR TITLE
feat: add binding for Context::SetPromiseHooks

### PR DESCRIPTION
**Pull request by legendecas**
Add support for `Context::SetPromiseHooks` for follow-up works of https://github.com/denoland/deno/pull/8209.

### CODE REVIEW

**Comment by legendecas** [comment]
As far as I could tell, add build flag `v8_enable_javascript_promise_hooks` should not break the `cached_data_version_tag` test. I can not reproduce it locally. 🤔

**Comment by bradfrosty** [comment]
@legendecas nice work on this PR! I'm curious about the web compatibility here, and the ability to leverage this API to replace something like zone.js. I know when they tried to standardize zones it ultimately fizzled out. Do you know if there's any reason why this API couldn't be leveraged within the browser?

**Comment by legendecas** [comment]
@bradfrosty for what I could tell, people at TC39 are concerned about the nature of the dynamic scope these APIs introducing to the language.

**Comment by legendecas** [comment]
Looks like I still can not reproduce the problem locally, or on my own fork's GitHub Action. Rebasing and trying to see if the problem still exists.

**Comment by legendecas** [comment]
anyone can help to approve the workflow to run? thanks

**Review by piscisaureus — APPROVED** [review]

**Pull request merged**
