### PR TITLE
Expand exclude for v8/tools

### PR DESCRIPTION
**Pull request by ry**
This was a failed attempt at fixing the windows build in Deno
See dc81cac3571649dda0149cae1b658c5dff25f8cc

# merge on approval

### CODE REVIEW

**Comment by piscisaureus** [comment]
I'm pretty sure it was erroring out for me because something in v8/tools was missing yesterday:

```
ninja: error: 'root/v8/tools/snapshot/asm_to_inline_asm.py', needed by 'gen/v8/embedded.cc', missing and no known rule to make it
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1
```

Are you really sure we don't need any of these file?

**Comment by ry** [comment]
No I'm not sure about it...

**Comment by piscisaureus** [comment]
This is what I get when I run `cargo package` with this patch applied:

```
     Running `D:\bartek\rusty_v8\target\package\rusty_v8-0.0.23\target\debug\build\rusty_v8-5bf1f1b70a7ecf84\build-script-build`
[rusty_v8 0.0.23] Downloading https://s3.amazonaws.com/deno.land/gn_ninja_binaries.tar.gz .......... Done.
[rusty_v8 0.0.23] using Chromiums clang
[rusty_v8 0.0.23] clang_base_path D:\bartek\rusty_v8\target\package\rusty_v8-0.0.23\target\debug\build\rusty_v8-4df80cff7ccdf583\out\clang
[rusty_v8 0.0.23] Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Win/clang-n332890-c2443155-1.tgz .......... Done.
[rusty_v8 0.0.23] Copying C:\Program Files (x86)/Microsoft Visual Studio/2017/Enterprise\DIA SDK\bin\amd64\msdia140.dll to D:\bartek\rusty_v8\target\package\rusty_v8-0.0.23\target\debug\build\rusty_v8-4df80cff7ccdf583\out\clang\bin
[rusty_v8 0.0.23] The current directory is D:\bartek\rusty_v8\target\package\rusty_v8-0.0.23
[rusty_v8 0.0.23] gn gen --root=D:\bartek\rusty_v8\target\package\rusty_v8-0.0.23 D:\bartek\rusty_v8\target\package\rusty_v8-0.0.23\target\debug\gn_out
[rusty_v8 0.0.23] running: "D:\\bartek\\rusty_v8\\target\\package\\rusty_v8-0.0.23\\target\\debug\\build\\rusty_v8-4df80cff7ccdf583\\out\\gn_ninja_binaries\\win\\gn.exe" "--root=D:\\bartek\\rusty_v8\\target\\package\\rusty_v8-0.0.23" "gen" "D:\\bartek\\rusty_v8\\target\\package\\rusty_v8-0.0.23\\target\\debug\\gn_out" "--args=is_debug=false clang_base_path=\"D:\\\\bartek\\\\rusty_v8\\\\target\\\\package\\\\rusty_v8-0.0.23\\\\target\\\\debug\\\\build\\\\rusty_v8-4df80cff7ccdf583\\\\out\\\\clang\" cc_wrapper=\"C:\\\\Users\\\\BertBelder\\\\.cargo\\\\bin\\\\sccache.EXE\" treat_warnings_as_errors=false"
[rusty_v8 0.0.23] Done. Made 137 targets from 78 files in 6097ms
[rusty_v8 0.0.23] cargo:rustc-env=GN_OUT_DIR=D:\bartek\rusty_v8\target\package\rusty_v8-0.0.23\target\debug\gn_out
[rusty_v8 0.0.23] running: "D:\\bartek\\rusty_v8\\target\\package\\rusty_v8-0.0.23\\target\\debug\\build\\rusty_v8-4df80cff7ccdf583\\out\\gn_ninja_binaries\\win\\ninja.exe" "-C" "D:\\bartek\\rusty_v8\\target\\package\\rusty_v8-0.0.23\\target\\debug\\gn_out" "rusty_v8"
[rusty_v8 0.0.23] ninja: Entering directory `D:\bartek\rusty_v8\target\package\rusty_v8-0.0.23\target\debug\gn_out'
[rusty_v8 0.0.23] ninja: error: '../../../v8/tools/snapshot/asm_to_inline_asm.py', needed by 'gen/v8/embedded.cc', missing and no known rule to make it
[rusty_v8 0.0.23] thread 'main' panicked at '
[rusty_v8 0.0.23] command did not execute successfully, got: exit code: 1
[rusty_v8 0.0.23]
[rusty_v8 0.0.23] build script failed, must exit now', C:\Users\BertBelder\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo_gn-0.0.15\src\lib.rs:203:3
```

**Comment by ry** [comment]
Maybe we should run cargo package as part of the tests here.

**Comment by piscisaureus** [comment]
> Maybe we should run cargo package as part of the tests here.

I was thinking that too. 
I'm now running `cargo package` on linux to see if this is maybe a windows specific issue.

**Comment by ry** [comment]
If we did that we could also ensure the .crate file is less than 10mb before publishing.

**Comment by piscisaureus** [comment]
Damn -- it seems that this `asm_to_inline_asm.py` script is not used on linux.
I was hoping to run it only on linux, but this means that we'd have test packaging on windows too. And it's so slow already...

**Comment by piscisaureus** [comment]
```


  action("asm_to_inline_asm_" + name) {
    visibility = [ ":*" ]  # Only targets in this file can depend on this.

    assert(emit_builtins_as_inline_asm)

    script = "tools/snapshot/asm_to_inline_asm.py"
    deps = [
      ":run_mksnapshot_" + name,
    ]
    sources = [
      "$target_gen_dir/embedded${suffix}.S",
    ]
    outputs = [
      "$target_gen_dir/embedded${suffix}.cc",
    ]
    args = invoker.args
    args += [
      rebase_path("$target_gen_dir/embedded${suffix}.S", root_build_dir),
      rebase_path("$target_gen_dir/embedded${suffix}.cc", root_build_dir),
    ]
  }
}
```

**Comment by ry** [comment]
@piscisaureus Yeah until we can figure out how to not have it rebuild each time, I think we'll just have to be careful.

BTW the lines in exclude in Cargo.toml that start with ! are ones to reinclude files that were excluded. It may be we can exclude all of v8/tools and simple re-include `asm_to_inline_asm.py`.

**Pull request merged**
