### PR TITLE
ci: update runner from ubuntu-latest-xl to ubuntu-20.04-xl

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Comment by piscisaureus** [comment]
We might need to set up sysroot.

**Comment by bartlomieju** [comment]
> We might need to set up sysroot.

Yikes, that's gonna be some more work. I can look into at the end of the week.

**Comment by bartlomieju** [comment]
Thanks @bnoordhuis

**Comment by piscisaureus** [comment]
We need to test whether Deno built with these rusty_v8 binaries still runs on Ubuntu 18.04.
I suspect the answer is no.

**Comment by piscisaureus** [comment]
> We need to test whether Deno built with these rusty_v8 binaries still runs on Ubuntu 18.04.

I tested it. Seems to work fine.

**Review by piscisaureus — APPROVED** [review]

**Pull request merged**
