### PR TITLE
Enable running on 32 bits and several minor fixes

### PR DESCRIPTION
**Pull request by PerfectLaugh**
This is the continuous effort of PR #752 
Should pass all test cases.

### CODE REVIEW

**Comment by bartlomieju** [comment]
Hi @PerfectLaugh, sorry for slow response. Could you please rebase this PR?

**Comment by PerfectLaugh** [comment]
> Hi @PerfectLaugh, sorry for slow response. Could you please rebase this PR?

Thanks for your reply. But I see slow or no motivation of this PR. This lets me worry.
If you kindly want to accept the PR. Please let me know. I can do my best to improve.

**Comment by bartlomieju** [comment]
@bnoordhuis any chance you could take a look? I'm not so knowledgable about various ABIs used in this PR.

**Review by bnoordhuis — APPROVED** [review]
Looks correct to me. Thanks for the PR.

**Pull request merged**
