### PR TITLE
Add bindings for String::kMaxLength / TypedArray::kMaxLength

### PR DESCRIPTION
**Pull request by RomainMuller**
Those are useful for pre-checking buffer sizes before attempting to create
a new String or typed array (or ArrayBuffer). Also useful for pre-allocating
possibly large chunks of memory safely.

### CODE REVIEW

**Comment by RomainMuller** [comment]
Note: wanted to have a test case around attempting to create a `TypedArray`/`ArrayBuffer` that is too long, but unlike `v8::String` factories, which return `null`/`None` when the buffer's too large, the `ArrayBuffer` constructor raises a fatal in this situation.

**Comment by piscisaureus** [comment]
> Note: wanted to have a test case around attempting to create a `TypedArray`/`ArrayBuffer` that is too long, but unlike `v8::String` factories, which return `null`/`None` when the buffer's too large, the `ArrayBuffer` constructor raises a fatal in this situation.

Can I suggest to add a smoke test for `TypedArray::max_lenght()` instead. Just assert that the returned value is somewhere in the range `2**30 <= max_length < 2**32`.

**Comment by piscisaureus** [comment]
> Note: wanted to have a test case around attempting to create a `TypedArray`/`ArrayBuffer` that is too long, but unlike `v8::String` factories, which return `null`/`None` when the buffer's too large, the `ArrayBuffer` constructor raises a fatal in this situation.

Interestingly on the JS side of things, a non-fatal RangeError is thrown:

```
> new Uint8Array(2**33-1)
Uncaught RangeError: Invalid typed array length: 8589934591
    at new Uint8Array (<anonymous>)
    at <anonymous>:2:1
```

**Comment by RomainMuller** [comment]
Added both:
- A range check test
- A JS test around the `RangeError` to work around the fatal

**Review by piscisaureus — APPROVED** [review]
LGTM, thanks @RomainMuller!

**Pull request merged**
