### PR TITLE
Error on warning

### PR DESCRIPTION
**Pull request by ry**

### CODE REVIEW

**Comment by piscisaureus** [comment]
Doesn't work? https://github.com/denoland/rusty_v8/runs/2469971866?check_suite_focus=true#step:11:103

**Comment by piscisaureus** [comment]
Probably caused by `--cap-lints warn`.

**Comment by ry** [comment]
> Doesn't work? https://github.com/denoland/rusty_v8/runs/2469971866?check_suite_focus=true#step:11:103

That link doesn't work for me (not sure why?) ... I'm not sure what you're referring to.

**Comment by piscisaureus** [comment]
> > Doesn't work? https://github.com/denoland/rusty_v8/runs/2469971866?check_suite_focus=true#step:11:103
> 
> That link doesn't work for me (not sure why?) ... I'm not sure what you're referring to.

```
2021-04-29T19:34:18.7132376Z ' CARGO_PKG_HOMEPAGE='https://github.com/rust-lang/libc' CARGO_PKG_LICENSE='MIT OR Apache-2.0' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=libc CARGO_PKG_REPOSITORY='https://github.com/rust-lang/libc' CARGO_PKG_VERSION=0.2.93 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=2 CARGO_PKG_VERSION_PATCH=93 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/home/runner/work/rusty_v8/rusty_v8/target/debug/deps:/usr/share/rust/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib:/home/runner/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib' OUT_DIR=/home/runner/work/rusty_v8/rusty_v8/target/aarch64-unknown-linux-gnu/debug/build/libc-5981779a3652720a/out rustc --crate-name libc /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.93/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=df8f42eb3d11a8f9 -C extra-filename=-df8f42eb3d11a8f9 --out-dir /home/runner/work/rusty_v8/rusty_v8/target/aarch64-unknown-linux-gnu/debug/deps --target aarch64-unknown-linux-gnu -C linker=/usr/bin/aarch64-linux-gnu-gcc-5 -L dependency=/home/runner/work/rusty_v8/rusty_v8/target/aarch64-unknown-linux-gnu/debug/deps -L dependency=/home/runner/work/rusty_v8/rusty_v8/target/debug/deps --cap-lints warn -D warnings --cfg freebsd11 --cfg libc_priv_mod_use --cfg libc_union --cfg libc_const_size_of --cfg libc_align --cfg libc_core_cvoid --cfg libc_packedN --cfg libc_cfg_target_vendor`
2021-04-29T19:34:18.7140174Z warning: trait objects without an explicit `dyn` are deprecated
2021-04-29T19:34:18.7148180Z ##[warning]   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/glob-0.3.0/src/lib.rs:294:32
2021-04-29T19:34:18.7158871Z     |
2021-04-29T19:34:18.7159998Z 294 |     fn cause(&self) -> Option<&Error> {
2021-04-29T19:34:18.7160537Z     |                                ^^^^^ help: use `dyn`: `dyn Error`
2021-04-29T19:34:18.7160970Z     |
2021-04-29T19:34:18.7161427Z     = note: `#[warn(bare_trait_objects)]` on by default
2021-04-29T19:34:18.7161777Z 
2021-04-29T19:34:18.7587222Z warning: use of deprecated associated function `std::error::Error::description`: use the Display impl or to_string()
2021-04-29T19:34:18.7590606Z ##[warning]   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/glob-0.3.0/src/lib.rs:291:20
2021-04-29T19:34:18.7592273Z     |
2021-04-29T19:34:18.7592831Z 291 |         self.error.description()
2021-04-29T19:34:18.7593399Z     |                    ^^^^^^^^^^^
2021-04-29T19:34:18.7593794Z     |
2021-04-29T19:34:18.7594535Z     = note: `#[warn(deprecated)]` on by default
2021-04-29T19:34:18.7594936Z 
2021-04-29T19:34:19.0769790Z warning: 2 warnings emitted
2021-04-29T19:34:19.0770261Z 
```

**Comment by ry** [comment]
Those are warnings from dependencies, `-D warnings` only applies to our code.

**Comment by piscisaureus** [comment]
@ry You're right, the code I pointed to is in third party code and therefore not relevant.

I confused though - how is it possible that this PR is green, while it doesn't include a fix for some warnings in *our* code that I landed a couple hours later (https://github.com/denoland/rusty_v8/commit/4b7f57081a6e2c91fb72b08f8f99ee86dda4aa97)?

If you've verified that it works though -- go ahead and land it.

**Review by piscisaureus — APPROVED** [review]

**Comment by ry** [comment]
Actually I submitted this patch to check if 4b7f57081 did actually fix warnings. I don't think that patch actually fixed anything - both because this PR didn't have errors and because we don't generally have warnings in rusty_v8. Maybe the author of 4b7f57081 was using nightly Rust.

We use `-D warning` in our other repos, and it works, so relatively sure this is correct.

**Pull request merged**
