### PR TITLE
Upgrade V8 to 8.1.310

### PR DESCRIPTION
**Pull request by ry**

### CODE REVIEW

**Comment by piscisaureus** [comment]
If you have to upgrade //build, please use merge and do not rebase.

**Comment by piscisaureus** [comment]
> If you have to upgrade //build, please use merge and do not rebase.

I have some script tooling for this so I just did that.

**Comment by ry** [comment]
> I have some script tooling for this so I just did that.

Can you land it? Even if it requires hacking - better to have it in the repo

**Comment by piscisaureus** [comment]
> Can you land it? Even if it requires hacking - better to have it in the repo

Currently looks like this: (I copy paste it into the terminal manually)

```
export COMMITDATE=2020-01-30T00:37:18.000Z

git submodule foreach 'git remote rm upstream; true' && 
git -C build remote add upstream https://chromium.googlesource.com/chromium/src/build &&
git -C buildtools remote add upstream https://chromium.googlesource.com/chromium/src/buildtools &&
git submodule foreach 'git remote add upstream `git remote get-url origin`; true' &&
git submodule foreach 'git remote update' &&
git submodule foreach 'export SHA=`git log upstream/master -n1 --until=$COMMITDATE --pretty=%H` && git merge $SHA -m "Merge commit $SHA from `git remote get-url upstream`"'

export BRANCH=20200130_rusty_v8
git -C build push git@github.com:denoland/chromium_build HEAD:refs/heads/$BRANCH
git -C buildtools push git@github.com:denoland/chromium_buildtools HEAD:refs/heads/$BRANCH
```

**Comment by piscisaureus** [comment]
There's an issue with it in the sense that it does not automatically include the v8 "release commit" because that's only pushed to a separate branch, and this script looks at master only.

**Comment by ry** [comment]
Fetched in submodule path 'buildtools', but it did not contain b7faa4551a207930cc5034cdfa2aacdfce6db142. Direct fetching of that commit failed.

**Pull request merged**
