### PR TITLE
Add support for generating a `clangd` compilation database

### PR DESCRIPTION
**Pull request by andreubotella**
This will help with IDE integration of the C++ part of the code.

Ref: https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/clangd.md

--------------

I've tested this on Linux and Windows, but I'll need someone to test on Mac for me.

### CODE REVIEW

**Review by ry — COMMENTED** [review]
This seems like a lot of code and cognitive overhead for something that relatively few people are going to be looking at. Maybe I'm not the right one to look at this tho, I don't use an IDE. I will let someone else review, but I'm -1.

**Comment by andreubotella** [comment]
As for "a lot of code", `tools/generate_compdb.py` is basically a combination of `tools/clang/scripts/generate_compdb.py` and `tools/clang/pylib/clang/compile_db.py`. The only real diff is:

```diff
def GetNinjaPath():
-   ninja_executable = 'ninja.exe' if sys.platform == 'win32' else 'ninja'
-   return os.path.join(
-       os.path.dirname(os.path.realpath(__file__)),
-         '..', '..', '..', '..', 'third_party', 'depot_tools', ninja_executable)
+   return 'ninja.exe' if sys.platform == 'win32' else 'ninja'
```

**Review by bnoordhuis — APPROVED** [review]
Like _I_ use an IDE. 😛

I don't have a need for this either but I'm also not super opposed. If it makes your life easier, I'll merge it.

**Comment by piscisaureus** [comment]
@bnoordhuis I see a yes from you, what's the holdup?

**Comment by bnoordhuis** [comment]
> I see a yes from you, what's the holdup?

Your review, really, but I'll take your comment as an implicit LGTM.

**Pull request merged**
