### PR TITLE
ArrayBuffer: add binding for IsResizableByUserJavaScript

### PR DESCRIPTION
**Pull request by levex**

### CODE REVIEW

**Review by littledivy — COMMENTED** [review]
Please add a test in `tests/test_api.rs`

**Review by bartlomieju — APPROVED** [review]
LGTM, once `rustfmt` passes :)

**Review by littledivy — APPROVED** [review]
LGTM!

**Comment by littledivy** [comment]
@levex Feel free to squash and merge if its ready.

**Pull request merged**
