### PR TITLE
build: apply 'win_crt_flavor_agnostic' flag to components built as static libraries

### PR DESCRIPTION
**Pull request by piscisaureus**
Depends on #709

### CODE REVIEW

**Comment by ry** [comment]
Seems like you're getting a link error.

Is this something that could be submitted upstream?

**Comment by piscisaureus** [comment]
> Is this something that could be submitted upstream?

No it's a "merge fix" to make #690 compatible again with `//build`.

**Review by ry — APPROVED** [review]

**Comment by piscisaureus** [comment]
Linking `oldnames.lib` (`println!("cargo:rustc-link-lib=dylib=oldnames")`) does work, but it seems that rustc somehow does not propagate this library, so if the PR is landed as-is Deno can no longer be built.

**Comment by piscisaureus** [comment]
... so we are out of options and will probably have to fork v8 forever.

**Pull request closed without merging**
