### PR TITLE
Weakable Globals & FFI Object Wrapping

### PR DESCRIPTION
**Pull request by Protryon**
This PR:
* Fixes an apparent non-deterministic test that depended on a script id
* Adds `Isolate::request_garbage_collection_for_testing` for GC-related tests
* Adds internal field support to `Object`s through:
    * `Object::internal_field_count`
    * `Object::get_internal_field` -- unsafe
    * `Object::set_internal_field` -- unsafe
    * `Object::get_internal_field_ptr` -- unsafe
    * `Object::set_internal_field_ptr` -- unsafe
    * `ObjectTemplate::internal_field_count`
    * `ObjectTemplate::set_internal_field_count`
    * The non-ptr variants could be made safe in the future by fully managing internal fields, but inside V8 the non-ptr and ptr variants overlap, so these have been marked unsafe.
* Adds a subset of weak support to `Global`s through:
    * `Global::set_weak`
    * `Global::is_weak`
    * `Global::clear_weak`

This PR partially addresses #304.

### CODE REVIEW

**Comment by ry** [comment]
@protryon Thanks - the patch generally looks good - except for ObjectWrap. It certainly looks useful but in rusty_v8 we’re trying to stick as close to the C++ API as possible. Could you remove it?

**Comment by Protryon** [comment]
@ry Done. I have made `Global::Weakable` a public unsafe trait in order to allow foreign implementation of analogs to `ObjectWrap`. I figure I'll publish a crate for `ObjectWrap` once this lands.

**Comment by piscisaureus** [comment]
@Protryon 

I'm generally in favor of adding these bindings; thank you so much for all the hard work you put into it.

However I have doubts about safely of auto-resetting "phantom" handles as it's done in the DefaultWeakable trait implementation. In Rust all types, including Globals, are freely movable; if the user moves the global to a different memory address V8 will not find out, risking memory corruption. I think that generally it is better to just provide weak callbacks and let the user decide what to do with them.

Second, it interferes a bit with an item on my roadmap which is to make Globals behave much more like Local handles. That is, they would not be allowed to be empty (use `Option<Global<T>>` instead for nullable handles) and it would not be mandatory to always convert them to Locals before they can be passed into various APIs. I believe it is possible to do this safely because the borrow checker can verify that a Global doesn't "disappear" while in use. If we let weak handles auto-reset that is no longer a possibility.

I believe a better solution would be to define a separate type for weak handles, much like the Arc/Weak split in Rust.

Now I won't be working on this very soon, and your patch generally looks solid, so I can land it in the meantime. However there is a risk that I might have to undo parts of it later on as we move forward with these plans.

**Comment by Protryon** [comment]
Replaced by #335 .

**Pull request closed without merging**
