### PR TITLE
feat: add v8__Isolate__GetCurrent

### PR DESCRIPTION
**Pull request by zhangyuang**
Ref [docs](https://v8docs.nodesource.com/node-4.8/d5/dda/classv8_1_1_isolate.html#a66324a6a0a257b62865065bf539fa442)
Support `v8::Isolate::get_current()`, we can get current isolate snapshot in a existed process

### CODE REVIEW

**Comment by littledivy** [comment]
@zhangyuang `rusty_v8` Isolates are `!Send` (cannot be sent between threads). See https://github.com/denoland/rusty_v8/issues/469. 
What is your usecase? Also, If this is added it should be marked `unsafe`.

**Comment by zhangyuang** [comment]
@littledivy I want to use it to get current snapshot in a nodejs program like [v8-profiler](https://github.com/hyj1991/v8-profiler-next/blob/316454184e536cfbc785818929fd033ea5cb9c8b/src/heap_profiler.cc#L77)

**Comment by littledivy** [comment]
If your program is single threaded use `thread_local` (See https://github.com/denoland/rusty_v8/issues/469#issuecomment-693215285).

**Comment by zhangyuang** [comment]
Thanks, I will try it later

**Comment by zhangyuang** [comment]
Excuse me, can you give me more entire demo?

`ISOLATE.with(|slot| slot.replace(Some(unsafe { transmute(*isolate) })));`

I don't know where is the isolate from?
image

**Comment by zhangyuang** [comment]
emmm, i think my purpose is not use isolate::new to create a new isolate but use current v8 isolate which is nodejs process executed

**Review by hengfeiyang — APPROVED** [review]

**Comment by littledivy** [comment]
See https://github.com/denoland/rusty_v8/issues/469 for why rusty_v8 doesn't bind `Isolate::GetCurrent`. Closing.

**Pull request closed without merging**
